main:
  - name: Accueil
    pageRef: /
    weight: 10
  - name: Ã€ propos
    pageRef: /a-propos
    weight: 20
  - name: Contact
    pageRef: /contact
    weight: 30
  - name: Newsletter
    url: https://newsletter.digibloom.net
    weight: 40
    params:
      external: true
